config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "index#index"
  get "/map", to: "map#index"
  get "/tuto", to: "tuto#index"

  resources :planet
  get "/planet/end/:id", to: "planet#end"
end

app/models/admin_user.rb
# frozen_string_literal: true

class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/association.rb
# frozen_string_literal: true

class Association < ApplicationRecord
  has_one_attached :image

  belongs_to :free
end

app/models/body_reaction.rb
# frozen_string_literal: true

class BodyReaction < ApplicationRecord
  has_many :planet_body_reactions
  has_many :planets, through: :planet_body_reactions

  has_one :emotion, dependent: :destroy
  accepts_nested_attributes_for :emotion, allow_destroy: true
end

app/models/choice.rb
# frozen_string_literal: true

class Choice < ApplicationRecord
  belongs_to :question
end

app/models/connect.rb
# frozen_string_literal: true

class Connect < ApplicationRecord
  has_many :planet_connects
  has_many :planets, through: :planet_connects

  has_one :definition, dependent: :destroy
  accepts_nested_attributes_for :definition, allow_destroy: true
end

app/models/definition.rb
# frozen_string_literal: true

class Definition < ApplicationRecord
  has_one_attached :emotion_image

  belongs_to :connect
end

app/models/emotion.rb
# frozen_string_literal: true

class Emotion < ApplicationRecord
  has_one_attached :body

  belongs_to :body_reaction

  has_many :reactions, dependent: :destroy
  accepts_nested_attributes_for :reactions, allow_destroy: true
end

app/models/free.rb
# frozen_string_literal: true

class Free < ApplicationRecord
  has_many :planet_frees
  has_many :planets, through: :planet_frees

  has_many :associations, dependent: :destroy
  accepts_nested_attributes_for :associations, allow_destroy: true
end

app/models/group.rb
# frozen_string_literal: true

class Group < ApplicationRecord
  has_one_attached :child
  has_one_attached :child_mad
  has_one_attached :object

  belongs_to :link
end

app/models/group_emotion.rb
# frozen_string_literal: true

class GroupEmotion < ApplicationRecord
  has_one_attached :body
  has_one_attached :emotion_file_one
  has_one_attached :emotion_file_two

  belongs_to :scratch
end

app/models/link.rb
# frozen_string_literal: true

class Link < ApplicationRecord
  has_many :planet_links
  has_many :planets, through: :planet_links

  has_many :groups, dependent: :destroy
  accepts_nested_attributes_for :groups, allow_destroy: true
end

app/models/list_emotion.rb
# frozen_string_literal: true

class ListEmotion < ApplicationRecord
end

app/models/membre_corp.rb
# frozen_string_literal: true

class MembreCorp < ApplicationRecord
end

app/models/memory_hard.rb
# frozen_string_literal: true

class MemoryHard < ApplicationRecord
  has_many :planet_memory_hards
  has_many :planets, through: :planet_memory_hards

  has_many :memory_hard_choices, dependent: :destroy
  accepts_nested_attributes_for :memory_hard_choices, allow_destroy: true
end

app/models/planet.rb
# frozen_string_literal: true

class Planet < ApplicationRecord
  has_one_attached :profil_picture
  has_one_attached :background_image

  has_many :planet_questions
  has_many :questions, through: :planet_questions
  accepts_nested_attributes_for :planet_questions, allow_destroy: true

  has_many :planet_memory_beginners
  has_many :memory_beginners, through: :planet_memory_beginners
  accepts_nested_attributes_for :planet_memory_beginners, allow_destroy: true

  has_many :planet_memory_hards
  has_many :memory_hards, through: :planet_memory_hards
  accepts_nested_attributes_for :planet_memory_hards, allow_destroy: true

  has_many :planet_body_reactions
  has_many :body_reactions, through: :planet_body_reactions
  accepts_nested_attributes_for :planet_body_reactions, allow_destroy: true

  has_many :planet_links
  has_many :links, through: :planet_links
  accepts_nested_attributes_for :planet_links, allow_destroy: true

  has_many :planet_connects
  has_many :connects, through: :planet_connects
  accepts_nested_attributes_for :planet_connects, allow_destroy: true

  has_many :planet_scratches
  has_many :scratches, through: :planet_scratches
  accepts_nested_attributes_for :planet_scratches, allow_destroy: true

  has_many :planet_frees
  has_many :frees, through: :planet_frees
  accepts_nested_attributes_for :planet_frees, allow_destroy: true
end

app/models/planet_free.rb
# frozen_string_literal: true

class PlanetFree < ApplicationRecord
  belongs_to :planet, optional: true
  belongs_to :free, optional: true
end

app/models/planet_link.rb
# frozen_string_literal: true

class PlanetLink < ApplicationRecord
  belongs_to :planet, optional: true
  belongs_to :link, optional: true
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  has_many :planet_questions
  has_many :planets, through: :planet_questions

  has_many :choices, dependent: :destroy
  accepts_nested_attributes_for :choices, allow_destroy: true
end

app/models/reaction.rb
# frozen_string_literal: true

class Reaction < ApplicationRecord
  has_one_attached :physic_reaction

  belongs_to :emotion
end

app/models/scratch.rb
# frozen_string_literal: true

class Scratch < ApplicationRecord
  has_many :planet_scratches
  has_many :planets, through: :planet_scratches

  has_one :group_emotion, dependent: :destroy
  accepts_nested_attributes_for :group_emotion, allow_destroy: true
end

app/controllers/planet_controller.rb
# frozen_string_literal: true

class PlanetController < ApplicationController
  def show
    @planet = Planet.find(params[:id])
    @questions = @planet.questions.all
    @memory_beginners = @planet.memory_beginners.all
    @memory_hards = @planet.memory_hards.all
    @body_reactions = @planet.body_reactions.all
    @links = @planet.links.all
    @connects = @planet.connects.all
    @scratches = @planet.scratches.all
    @frees = @planet.frees.all
  end

  def end
    @planet = Planet.find(params[:id])
  end
end

app/helpers/index_helper.rb
# frozen_string_literal: true

module IndexHelper
  def show_svg(path)
    File.open(path, "rb") do |file|
      raw file.read
    end
    end
end

app/views/planet/end.html.erb
<% content_for :body_class, "level end left" %>

<%= link_to image_tag("/assets/rocketbtn.svg"), map_path, class: "backMap" %>
<%= link_to "Accueil", map_path, class: "backMenu" %>

<img src="/assets/starship.svg" class="starship" alt="Fusée" />
<div class="bull">
    <div class="bullTitle">Roquette</div>
    <p class="starshipText"><%= @planet.end_text %></p>
    <img src="/assets/bull-shape.svg" class="bullShape" alt="Tracé bulle" />
</div>

<% if @planet.background_image.attached? %>
    <%= image_tag @planet.background_image, class: "levelBackground" %>
<% end %>

app/views/planet/show.html.erb
<% content_for :body_class, "level" %>

<div id="cross"><%= link_to image_tag("/assets/baseline-clear.svg"), map_path()  %></div>

<%= image_tag "/assets/bravo.svg", class: "bravo" %>


<% if @questions.any? %>
    <% @questions.each do |question| %>
        <div class="gameContainer">
            <div class="gameCard question">
                <div class="step">
                    <span class="state">1</span>/<span class="stateEnd">4</span>
                </div>
                <div class="entitled" ><%= question.entitled %></div>
                <div class="situation" ><%= question.situation %></div>
                <div class="list-solutions">
                    <% question.choices.each do |choice|%>
                        <% if choice.true == true %>
                            <div class="solution" id="true">
                        <% else %>
                            <div class="solution">
                        <% end %>
                                <%= image_tag("/assets/#{choice.answer}.svg") %>
                                <div class="<%= choice.answer %>"><%= choice.answer.capitalize %></div>
                        </div>
                    <% end %>
                </div>

                <div class="none answer-explication">
                    <% question.choices.each do |choice|%>
                        <% if choice.true == true %>
                            <%= image_tag("/assets/#{choice.answer}.svg") %>
                            <div class="sub-explanation"><%= question.explanation_title %></div>
                            <div class="explanation"><%= question.explanation %></div>
                            <p class="next button-base">Continuer<p>
                        <% end %>
                    <% end %>
                </div>

            </div>
        </div>
    <% end %>
<% end %>

<% if @connects.any? %>
    <% @connects.each do |connect| %>
        <div class="gameContainer">
            <div class="gameCard connect">
                <div class="step">
                    <span class="state">1</span>/<span class="stateEnd">4</span>
                </div>
                <div class="entitled" ><%= connect.entitled %></div>
                    <div class="definition" id="<%= connect.definition.text %>"><%= connect.definition.entitled %></div>
                    <div class="emotionButton peur">Peur</div>
                    <div class="emotionButton tristesse">Tristesse</div>
                    <div class="emotionButton colere">Colère</div>
                    <div class="emotionButton surprise">Surprise</div>
                    <div class="emotionButton degout">Degout</div>
                    <div class="emotionButton joie">Joie</div>
                <p id="next_connect" class="next button-base none">Continuer<p>
            </div>
        </div>
    <% end %>
<% end %>


<% if @frees.any? %>
    <% @frees.each do |free| %>
        <div class="gameContainer">
            <div class="gameCard free">
                <% @frees.each do |free| %>
                    <% free.associations.each do |association|%>
                        <div class="popup none" id="popup-<%= association.id %>">
                            <div class="text"><%= association.solution %></div>
                            <%= image_tag association.image, class: "child" %>
                            <div class="back">Retourner au jeu </div>
                        </div>
                    <% end %>
                <% end %>
                <div class="entitled" ><%= free.entitled %></div>
                <div class="definitions">
                    <% free.associations.each do |association|%>
                        <div class="definition">
                            <div><%= image_tag association.image, class: "picture" %></div>
                            <div class="text"><%= association.definition %></div>
                            <div id="<%= association.id%>" class="slot"></div>
                        </div>
                    <% end %>
                </div>
                <div class="solutions">
                    <% free.associations.shuffle.each do |association|%>
                        <div class="solution" id="<%= association.id%>">
                            <%= image_tag("/assets/#{association.emotion}.svg", class: "emotionImg") %>
                            <div class="text"><%= association.emotion %></div>
                        </div>
                    <% end %>                      
                </div>
                <p id="next_connect" class="next button-base none">Continuer<p>
            </div>
        </div>
    <% end %>
<% end %>


<% if @memory_beginners.any? %>
    <% @memory_beginners.each do |memory_beginner| %>
    <div class="gameContainer">
        <div class="gameCard memory">
            <% memory_beginner.memory_beginner_choices.each do |choice|%>
                <div class="popup none" id="popup-<%= choice.id %>">
                    <%= image_tag choice.card, class: "child" %>
                    <div class="text"><%= choice.answer %></div>
                    <div class="text-sub"><%= choice.answer_sub %></div>
                    <div class="back">Retourner au jeu </div>
                </div>
            <% end %>
            <div class="entitled" ><%= memory_beginner.entitled %></div>
                <% memory_beginner.memory_beginner_choices.shuffle.each do |choice|%>
                    <div id = "<%= choice.id %>" class="memoryCard lorem">
                        <div class="cardReveal"><%= image_tag choice.card %></div>
                        <div class="cardBack"><%= image_tag("/assets/back-card.svg") %></div>
                    </div>
                <% end %>
                <% memory_beginner.memory_beginner_choices.shuffle.each do |choice|%>
                    <div id = "<%= choice.id %>" class="memoryCard ipsum">
                        <div class="cardReveal"><%= image_tag choice.card %></div>
                        <div class="cardBack"><%= image_tag("/assets/back-card.svg") %></div>
                    </div>
                <% end %>
                <p id="next_connect" class="next button-base none">Continuer<p>
            </div>
        </div>
    <% end %>
<% end %>



<% if @memory_hards.any? %>
<div class="gameContainer">
    <div class="gameCard memory">
        <% @memory_hards.each do |memory_hard| %>
        <div class="entitled" ><%= memory_hard.entitled %></div>
            <% memory_hard.memory_hard_choices.each do |choice|%>
                <div class="memoryCard lorem">
                    <div class="cardReveal"><%= image_tag choice.card_one %></div>
                    <div class="cardBack"><%= image_tag("/assets/back-card.svg") %></div>
                </div>
                <div class="memoryCard ipsum">
                    <div class="cardReveal"><%= image_tag choice.card_two %></div>
                    <div class="cardBack"><%= image_tag("/assets/back-card.svg") %></div>
                </div>
            <% end %>
        <% end %>
    </div>
</div>
<% end %>



<% if @body_reactions.any? %>
    <% @body_reactions.each do |body_reaction| %>
        <div class="gameContainer">
            <div class="gameCard bodyAction">
            <%# <%= body_reaction.name %>
            <div class="step">
                    <span class="state">1</span>/<span class="stateEnd">4</span>
            </div>
            <div class="entitled" ><%= body_reaction.entitled %></div>
                <p class="emotionName"><%= body_reaction.emotion.name %></p>
                <%= image_tag body_reaction.emotion.body, class: "body" %>
                <%= image_tag(("/assets/bouche.svg"), :class => "emotionLink bouche", id: "bouche") %>
                <%= image_tag(("/assets/bras.svg"), :class => "emotionLink bras", id: "bras") %>
                <%= image_tag(("/assets/coeur.svg"), :class => "emotionLink coeur", id: "coeur") %>
                <%= image_tag(("/assets/dents.svg"), :class => "emotionLink dents", id: "dents") %>
                <%= image_tag(("/assets/epaule.svg"), :class => "emotionLink epaule", id: "epaule") %>
                <%= image_tag(("/assets/mains.svg"), :class => "emotionLink mains", id: "mains") %>
                <%= image_tag(("/assets/tete.svg"), :class => "emotionLink tete", id: "tete") %>
                <%= image_tag(("/assets/ventre.svg"), :class => "emotionLink ventre", id: "ventre") %>

                <div id="reactions">

                    <% body_reaction.emotion.reactions.each do |reaction|%>
                        <div class="reactionGroup" id="<%= reaction.name %>">
                            <%= image_tag reaction.physic_reaction, class: "reactionPicture" %>
                            <p class="reactionName"><%= reaction.description %></p>
                        </div>
                    <% end %>

                </div>
            <p id="next_connect" class="next button-base none">Continuer<p> 
            </div>
        </div>
    <% end %>
<% end %>



<% if @links.any? %>
<div class="gameContainer">
    <div class="gameCard likeUnlike">
        <% @links.each do |link| %>
            <% link.groups.each do |group|%>
                <div class="popup none" id="popup-<%= group.id %>">
                    <div class="text"><%= group.solution %></div>
                    <%= image_tag group.child, class: "child" %>
                    <div class="back">Retourner au jeu </div>
                </div>
                <div class="popup-wrong none" id="popup-wrong-<%= group.id %>">
                    <div class="text"><%= group.error %></div>
                    <%= image_tag group.child_mad, class: "child" %>
                    <div class="back">Retourner au jeu </div>
                </div>
            <% end %>
        <% end %>
        <% @links.each do |link| %>
            <div class="entitled" ><%= link.entitled %></div>
            <%# <%= link.name %>
            <% link.groups.each do |group|%>
                <%= image_tag group.child, class: "child", id: "#{group.id}" %>
                <%= image_tag group.object, class: "object", id: "#{group.id}" %>
                <%# <%= group.solution %>
                <%# <%= group.error %>
            <% end %>
        <% end %>
    <p id="next_connect" class="next button-base none">Continuer<p> 
    </div>
</div>
<% end %>






<% if @scratches.any? %>
    <% @scratches.each do |scratche| %>
        <div class="gameContainer">
            <div class="gameCard maskedEmotions"> 
                <div class="popup none">
                    <div class="group_img">
                        <%= image_tag scratche.group_emotion.emotion_file_one, class: "img" %>
                        <%= image_tag scratche.group_emotion.emotion_file_two, class: "img" %>
                    </div>
                    <div class="text"><%= scratche.group_emotion.solution_title %></div>
                    <div class="text-sub"><%= scratche.group_emotion.emotion %></div>
                    <p id="next_connect" class="next button-base none">Continuer<p> 
                </div> 
                <div class="step">
                    <span class="state">1</span>/<span class="stateEnd">4</span>
                </div> 
                <div class="entitled" ><%= scratche.entitled %></div>
                    <div class="situation" ><%= scratche.group_emotion.situation %></div>
                    <%= image_tag scratche.group_emotion.body, class: "body" %>
                    <div class="cloudContainer visible">
                        <img src="/assets/cloud-reveal.svg" class="cloud reveal" alt="Pensée" />
                        <img src="/assets/cloud.svg" class="cloud initial" alt="Pensée" />
                        <%= image_tag scratche.group_emotion.emotion_file_one, class: "emotion emotion-1" %>
                        <%= image_tag scratche.group_emotion.emotion_file_two, class: "emotion emotion-2" %>
                    </div>
            </div>
        </div>
    <% end %>
<% end %>



<% if @planet.background_image.attached? %>
    <%= image_tag @planet.background_image, class: "levelBackground" %>
<% end %>