config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "index#index"
  get "/map", to: "map#index"
  get "/tuto", to: "tuto#index"

  resources :planet
  get "/planet/end/:id", to: "planet#end"
end

app/models/admin_user.rb
# frozen_string_literal: true

class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/association.rb
# frozen_string_literal: true

class Association < ApplicationRecord
  has_one_attached :image

  belongs_to :free
end

app/models/body_reaction.rb
# frozen_string_literal: true

class BodyReaction < ApplicationRecord
  has_many :planet_body_reactions
  has_many :planets, through: :planet_body_reactions

  has_one :emotion, dependent: :destroy
  accepts_nested_attributes_for :emotion, allow_destroy: true
end

app/models/choice.rb
# frozen_string_literal: true

class Choice < ApplicationRecord
  belongs_to :question
end

app/models/connect.rb
# frozen_string_literal: true

class Connect < ApplicationRecord
  has_many :planet_connects
  has_many :planets, through: :planet_connects

  has_one :definition, dependent: :destroy
  accepts_nested_attributes_for :definition, allow_destroy: true
end

app/models/definition.rb
# frozen_string_literal: true

class Definition < ApplicationRecord
  has_one_attached :emotion_image

  belongs_to :connect
end

app/models/emotion.rb
# frozen_string_literal: true

class Emotion < ApplicationRecord
  has_one_attached :body

  belongs_to :body_reaction

  has_many :reactions, dependent: :destroy
  accepts_nested_attributes_for :reactions, allow_destroy: true
end

app/models/free.rb
# frozen_string_literal: true

class Free < ApplicationRecord
  has_many :planet_frees
  has_many :planets, through: :planet_frees

  has_many :associations, dependent: :destroy
  accepts_nested_attributes_for :associations, allow_destroy: true
end

app/models/group.rb
# frozen_string_literal: true

class Group < ApplicationRecord
  has_one_attached :child
  has_one_attached :child_mad
  has_one_attached :object

  belongs_to :link
end

app/models/link.rb
# frozen_string_literal: true

class Link < ApplicationRecord
  has_many :planet_links
  has_many :planets, through: :planet_links

  has_many :groups, dependent: :destroy
  accepts_nested_attributes_for :groups, allow_destroy: true
end

app/models/list_emotion.rb
# frozen_string_literal: true

class ListEmotion < ApplicationRecord
end

app/models/membre_corp.rb
# frozen_string_literal: true

class MembreCorp < ApplicationRecord
end

app/models/memory_hard.rb
# frozen_string_literal: true

class MemoryHard < ApplicationRecord
  has_many :planet_memory_hards
  has_many :planets, through: :planet_memory_hards

  has_many :memory_hard_choices, dependent: :destroy
  accepts_nested_attributes_for :memory_hard_choices, allow_destroy: true
end

app/models/planet.rb
# frozen_string_literal: true

class Planet < ApplicationRecord
  has_one_attached :profil_picture
  has_one_attached :background_image

  has_many :planet_questions
  has_many :questions, through: :planet_questions
  accepts_nested_attributes_for :planet_questions, allow_destroy: true

  has_many :planet_memory_beginners
  has_many :memory_beginners, through: :planet_memory_beginners
  accepts_nested_attributes_for :planet_memory_beginners, allow_destroy: true

  has_many :planet_memory_hards
  has_many :memory_hards, through: :planet_memory_hards
  accepts_nested_attributes_for :planet_memory_hards, allow_destroy: true

  has_many :planet_body_reactions
  has_many :body_reactions, through: :planet_body_reactions
  accepts_nested_attributes_for :planet_body_reactions, allow_destroy: true

  has_many :planet_links
  has_many :links, through: :planet_links
  accepts_nested_attributes_for :planet_links, allow_destroy: true

  has_many :planet_connects
  has_many :connects, through: :planet_connects
  accepts_nested_attributes_for :planet_connects, allow_destroy: true

  has_many :planet_scratches
  has_many :scratches, through: :planet_scratches
  accepts_nested_attributes_for :planet_scratches, allow_destroy: true

  has_many :planet_frees
  has_many :frees, through: :planet_frees
  accepts_nested_attributes_for :planet_frees, allow_destroy: true
end

app/models/planet_free.rb
# frozen_string_literal: true

class PlanetFree < ApplicationRecord
  belongs_to :planet, optional: true
  belongs_to :free, optional: true
end

app/models/planet_link.rb
# frozen_string_literal: true

class PlanetLink < ApplicationRecord
  belongs_to :planet, optional: true
  belongs_to :link, optional: true
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  has_many :planet_questions
  has_many :planets, through: :planet_questions

  has_many :choices, dependent: :destroy
  accepts_nested_attributes_for :choices, allow_destroy: true
end

app/models/reaction.rb
# frozen_string_literal: true

class Reaction < ApplicationRecord
  has_one_attached :physic_reaction

  belongs_to :emotion
end

app/models/scratch.rb
# frozen_string_literal: true

class Scratch < ApplicationRecord
  has_many :planet_scratches
  has_many :planets, through: :planet_scratches

  has_one :group_emotion, dependent: :destroy
  accepts_nested_attributes_for :group_emotion, allow_destroy: true
end

app/controllers/map_controller.rb
# frozen_string_literal: true

class MapController < ApplicationController
  def index
    @planets = Planet.all.order("id")
  end
end

app/helpers/index_helper.rb
# frozen_string_literal: true

module IndexHelper
  def show_svg(path)
    File.open(path, "rb") do |file|
      raw file.read
    end
    end
end

app/views/map/index.html.erb
<% content_for :body_class, "map space noAnimation" %>
<div class="starsBackground"></div>

<img src="/assets/logoSimple.svg" class="logoSimple" alt="Logo Destination Emotions simple" />

<% @planets.each do |planet| %>
    <%= link_to planet_path(planet.id), :action => 'go' do %>
        <div class="planet">
            <% if planet.profil_picture.attached? %>
                <div class="planetPicture"><%= image_tag planet.profil_picture %></div>
            <% end %>
            <%= link_to planet.name, planet_path(planet.id), :class => "planetName" %>
        </div>
    <% end %>
<% end %>
<div class="arrow arrowLeft"><img src="/assets/back.svg" class="icon" alt="icon" /></div>
<div class="arrow arrowRight"><img src="/assets/back.svg" class="icon" alt="icon" /></div>

<div class="helpButton"><img src="/assets/helpButton.svg" class="icon" alt="icon" /></div>

<div class="emotionsPopup">
    <div class="gameCard">
        <div class="entitled">Les 6 émotions principales</div>
        <div class="emotions">
            <div class="emotion tristesse">
                <img src="/assets/carteTriste.svg" class="icon" alt="icon" />
                <p class="name">Tristesse</p>
                <p class="description">C’est une baisse de ton énergie, de ton humeur. Quand tu es triste, tu perds ton appétit, tes forces, ton enthousiasme.</p>
            </div>

            <div class="emotion joie">
                <img src="/assets/carteJoie.svg" class="icon" alt="icon" />
                <p class="name">Joie</p>
                <p class="description">Sensation très agréable provoquée par quelque chose qui te fait plaisir. </p>
            </div>

            <div class="emotion degout">
                <img src="/assets/carteDegout.svg" class="icon" alt="icon" />
                <p class="name">Dégoût</p>
                <p class="description">C’est ce que tu ressens face à quelque chose que tu n’aimes pas. Tu ne veux alors pas t’en approcher, ni le toucher.</p>
            </div>

            <div class="emotion colere">
                <img src="/assets/carteColere.svg" class="icon" alt="icon" />
                <p class="name">Colère</p>
                <p class="description">C’est une sensation très rapide qui s’empare de toi, t’empêchant de réfléchir. Elle te pousse à réagir comme un animal attaqué.</p>
            </div>

            <div class="emotion surprise">
                <img src="/assets/carteSurprise.svg" class="icon" alt="icon" />
                <p class="name">Surprise</p>
                <p class="description">C’est une émotion déclenchée par un imprévu, quelque chose de nouveau. Elle s’associe souvent avec d’autres émotions comme la joie ou la colère.</p>
            </div>

            <div class="emotion peur">
                <img src="/assets/cartePeur.svg" class="icon" alt="icon" />
                <p class="name">Peur</p>
                <p class="description">La peur apparaît quand tu crois qu’il va t’arriver du mal. Par exemple, si tu es poursuivi(e) par un dragon !</p>
            </div>
        </div>
        <div class="closeButton">Fermer</div>
    </div>
</div>

<div class="bottomInfo">
    <p>💡 Lorsque tu ne comprends pas quelque chose, demande à un adulte</p>
</div>